name: BingoPlus
version: '${version}'
main: com.stimmie.bingoplus.BingoPlus
api-version: '1.21'
description: Gamble any item with a chance to win, but the house always wins!
commands:
  bingoplus:
    description: Opens the gamble GUI or gambles the item in your hand.
    usage: /bingoplus [hand]
    permission: bingoplus.gamble
    aliases: [gamble]
permissions:
  bingoplus.gamble:
    description: Allows you to gamble items.
    default: true
